apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python app that displays time.
  annotations:
    github.com/project-slug: RubenLopSol/python-app
    backstage.io/techdocs-ref: dir:. # mkdocs
spec:
  type: service
  owner: group:default/development
  lifecycle: experimental